<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Data-Analytics-Lifecycle" data-toc-modified-id="Data-Analytics-Lifecycle-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Data Analytics Lifecycle</a></span></li><li><span><a href="#ETL-(Extract-Transform-Loading):-What?-Why?" data-toc-modified-id="ETL-(Extract-Transform-Loading):-What?-Why?-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>ETL (Extract Transform Loading): What? Why?</a></span><ul class="toc-item"><li><span><a href="#Garbage-In,-Garbage-Out" data-toc-modified-id="Garbage-In,-Garbage-Out-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Garbage In, Garbage Out</a></span></li></ul></li><li><span><a href="#How-much-time-do-data-analysts-spend-cleaning-and-transforming-data?" data-toc-modified-id="How-much-time-do-data-analysts-spend-cleaning-and-transforming-data?-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>How much time do data analysts spend cleaning and transforming data?</a></span></li><li><span><a href="#This-ETL-module-will-cover:" data-toc-modified-id="This-ETL-module-will-cover:-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>This ETL module will cover:</a></span></li><li><span><a href="#Different-data-types" data-toc-modified-id="Different-data-types-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Different data types</a></span></li><li><span><a href="#Basic-ETL-techniques" data-toc-modified-id="Basic-ETL-techniques-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Basic ETL techniques</a></span></li><li><span><a href="#Titanic-Dataset" data-toc-modified-id="Titanic-Dataset-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Titanic Dataset</a></span></li><li><span><a href="#Essential-Data-Transformation" data-toc-modified-id="Essential-Data-Transformation-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Essential Data Transformation</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Finding-out-data-type-&amp;-missing-values" data-toc-modified-id="Finding-out-data-type-&amp;-missing-values-8.0.1"><span class="toc-item-num">8.0.1&nbsp;&nbsp;</span>Finding out data type &amp; missing values</a></span></li><li><span><a href="#Basic-statistics" data-toc-modified-id="Basic-statistics-8.0.2"><span class="toc-item-num">8.0.2&nbsp;&nbsp;</span>Basic statistics</a></span></li><li><span><a href="#Remove-(unnessary)-columns" data-toc-modified-id="Remove-(unnessary)-columns-8.0.3"><span class="toc-item-num">8.0.3&nbsp;&nbsp;</span>Remove (unnessary) columns</a></span></li><li><span><a href="#Handling-missing-value" data-toc-modified-id="Handling-missing-value-8.0.4"><span class="toc-item-num">8.0.4&nbsp;&nbsp;</span>Handling missing value</a></span></li><li><span><a href="#Handling-Inaccurate/Inconsistent-Data" data-toc-modified-id="Handling-Inaccurate/Inconsistent-Data-8.0.5"><span class="toc-item-num">8.0.5&nbsp;&nbsp;</span>Handling Inaccurate/Inconsistent Data</a></span></li></ul></li></ul></li><li><span><a href="#Intermediate-level-Data-Transformation" data-toc-modified-id="Intermediate-level-Data-Transformation-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Intermediate-level Data Transformation</a></span></li></ul></div>

## Nicole Becker, "On my honor, as a student, I have neither given nor received unauthorized aid on this academic work."

# Data Analytics Lifecycle

In [1]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://upload.wikimedia.org/wikipedia/commons/b/b9/CRISP-DM_Process_Diagram.png")

In [2]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "http://www.dataprix.com/files/CRISPDM/Metodologia_CRISP_DM1_html_52cdbecf.png")

**Data understanding and data preparation** are two important phases in data analytics project. 

These two stages are also called **"Extract Transform Loading" (ETL)**

# ETL (Extract Transform Loading): What? Why?
ETL represents a broad range of data transformation and processing techniques. ETL involves cleaning and transforming the data for data analysis. 

## Garbage In, Garbage Out##

Similar terms include **data munging**, **wrangling**, and **data transformation**

* Original data are not ready for analysis
* A typical data set or source contains many data quality issues
    * Missing values
    * Inconsistency
    * Inaccuracy
    * …
* Data preparation (or transformation) is a must

<img src="images\etl.gif">

# How much time do data analysts spend cleaning and transforming data?

<img src="images/Time1.jpg">
<img src="images/Time2.jpg">

# This ETL module will cover:

* Basic techniques (data cleaning) 
* Intermediate-level techniques (data transformation)
* Advanced techniques (data integration)

# Different data types

* **Numerical** refers to integer and real
    * Integer number (int): age
    * Real number (float): price
* **Object (or string)**
    * **Nominal** or polynominal means there are more than two different values in the attributes. For example, Maritial_Status (single, married, divorced), school year (freshman, sophomore, junior, senior)
    * **Binominal** means only two values. For example, Exam grade (Pass, Fail), Admission (Acceptance, Rejection), Purchase (Yes, Or), Cheating (True, False)


# Basic ETL techniques
This covers basic ETL techniques

Relevant online resources: 10 Minutes to pandas 
* Numerical columns http://pandas.pydata.org/pandas-docs/stable/10min.html
* Categorical columns http://pandas-docs.github.io/pandas-docs-travis/categorical.html

In [3]:
from IPython.display import YouTubeVideo
YouTubeVideo('DNyKDI9pn0Q')

# Titanic Dataset

<img src="images\titanic_datadescription.gif">

In [4]:
# import python packages
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

In [5]:
# import titanic_train.csv
ti=pd.read_csv("data/titanic_train.csv")
ti.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex     Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22.00      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  350.00      1   
2                             Heikkinen, Miss. Laina      hi   26.00      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   hello   35.00      1   
4                           Allen, Mr. William Henry    male    0.35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# Essential Data Transformation

### Finding out data type & missing values

In [6]:
#data types & missing values
ti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


**Numerical columns**: PassengerId, Survived, Pclass, Age, SibSp, Parch, Fare

**Categorial columns**: Name, Sex, Ticket, Cabin, Embarked

There are some **missing values (Age, Cabin, Embarked)**

**This dataset needs data cleaning & transformation**

### Basic statistics

In [7]:
#Describe shows a quick statistic summary of your data
#this is a good way to examine the numerical columns
ti.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   30.087563    0.523008   
std     257.353842    0.486592    0.836071   18.863424    1.102743   
min       1.000000    0.000000    1.000000    0.350000    0.000000   
25%     223.500000    0.000000    2.000000   20.000000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000  350.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

There are a number of **data quality issues**
- Someone or some people are 350 years old 

In [8]:
ti.hist(figsize=(8,8))

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x00000153D1ACD0F0>,
      dtype=object)

In [9]:
# describe for a single column
ti['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [10]:
# do this for categorical columns
ti['Embarked'].describe()

count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

- Three different ports of departure (C = Cherbourg; Q = Queenstown; S = Southhampton)
- S is the most popular port. 644 boared on Titanic from S

In [11]:
ti.groupby('Embarked').size()

Embarked
C    168
Q     77
S    644
dtype: int64

In [12]:
# how many unique values in the Sex column
ti.groupby('Sex').size()

Sex
female    312
hello       1
hi          1
male      577
dtype: int64

** Is there any data quality issue here?** 

** There's an issue with the results - "hi" and "hello" should not be a sex **

### Remove (unnessary) columns

In [13]:
# remove an unnecessary column (PassengerId)

ti = ti.drop('PassengerId', axis=1)
ti.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex     Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    male   22.00      1      0         A/5 21171   7.2500   NaN        S  
1  female  350.00      1      0          PC 17599  71.2833   C85        C  
2      hi   26.00      0      0  STON/O2. 3101282   7.9250   NaN        S  
3   hello   35.00      1      0            113803  53.1000  C123        S  
4    male    0.35      0      0            373450   8.0500   NaN        S

In [14]:
# remove multiple columns (Name, Ticket, Cabin)

ti = ti.drop(['Name','Ticket'], axis=1)
ti.head()

Survived  Pclass     Sex     Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male   22.00      1      0   7.2500   NaN        S
1         1       1  female  350.00      1      0  71.2833   C85        C
2         1       3      hi   26.00      0      0   7.9250   NaN        S
3         1       1   hello   35.00      1      0  53.1000  C123        S
4         0       3    male    0.35      0      0   8.0500   NaN        S

In [15]:
# can you remove Cabin column? (this column is not much useful for further analysis - predictive analytics)
ti = ti.drop(['Cabin'], axis=1)
ti.head()

Survived  Pclass     Sex     Age  SibSp  Parch     Fare Embarked
0         0       3    male   22.00      1      0   7.2500        S
1         1       1  female  350.00      1      0  71.2833        C
2         1       3      hi   26.00      0      0   7.9250        S
3         1       1   hello   35.00      1      0  53.1000        S
4         0       3    male    0.35      0      0   8.0500        S

In [16]:
# how many missing values in each column or variable
ti.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

### Handling missing value

There are different ways to handle missing values
- drop them all
- replace with certain values (e.g., mean, mode, median, specific value)

Recommended heuristics for handling missing values in real-world datasets

1. Remove unnecessary (or unmeaningful) columns (e.g., Ticket number): "unnecessary" means those columns you don't consider for the analysis. For example, it is obvious that there is no need to analyze "ticker numbers".
2. Some columns' missing values could be replaced with a specific value (e.g., mean, median), while replacement is not possible for other columns. For the latter case, drop the rows with missing values "mindfully". 

In [17]:
#handling missing value: remove the rows with any missing value
ti_rev = ti.dropna()
ti_rev.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 8 columns):
Survived    712 non-null int64
Pclass      712 non-null int64
Sex         712 non-null object
Age         712 non-null float64
SibSp       712 non-null int64
Parch       712 non-null int64
Fare        712 non-null float64
Embarked    712 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 50.1+ KB


Now, the dataset has 712 rows. No rows with missing values. This is an aggressive approach.

In [18]:
# replace null value with the most popular value in a categorial columns
ti = ti.fillna({'Embarked': 'S'})
ti.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64

In [19]:
ti['Age'].median()

28.0

In [20]:
# replace null value with the median value 
ti = ti.fillna({'Age': 28})
ti.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [21]:
# what would you do to replace null values with the mean value
#find mean value
ti['Age'].mean()

29.67286195286195

In [22]:
#replace null with mean value
ti = ti.fillna({'Age': 3})
ti.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

### Handling Inaccurate/Inconsistent Data
- replace inaccurate values with null values and remove the row(s) with missing values
- replace inaccurate values with different values

In [23]:
# hello in Sex is inaccurate ...replacing inaccurate value with null value
ti = ti.replace('hello', np.nan)
ti.head()

Survived  Pclass     Sex     Age  SibSp  Parch     Fare Embarked
0         0       3    male   22.00      1      0   7.2500        S
1         1       1  female  350.00      1      0  71.2833        C
2         1       3      hi   26.00      0      0   7.9250        S
3         1       1     NaN   35.00      1      0  53.1000        S
4         0       3    male    0.35      0      0   8.0500        S

In [24]:
ti = ti.dropna()
ti.head()

Survived  Pclass     Sex     Age  SibSp  Parch     Fare Embarked
0         0       3    male   22.00      1      0   7.2500        S
1         1       1  female  350.00      1      0  71.2833        C
2         1       3      hi   26.00      0      0   7.9250        S
4         0       3    male    0.35      0      0   8.0500        S
5         0       3    male   28.00      0      0   8.4583        Q

In [25]:
# 350 is an inaccurate value for age and should be replaced by 35
# changinge single value with replace
ti = ti.replace({'Age': 350}, {'Age': 35})
ti.head()

Survived  Pclass     Sex    Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.00      1      0   7.2500        S
1         1       1  female  35.00      1      0  71.2833        C
2         1       3      hi  26.00      0      0   7.9250        S
4         0       3    male   0.35      0      0   8.0500        S
5         0       3    male  28.00      0      0   8.4583        Q

In [26]:
# instead of replacing hello with null value and removing the row, 
# can you replace hi with the most popular value (male) in the categorical column?

In [27]:
#find most popular value
ti.groupby('Sex').size()

Sex
female    312
hi          1
male      577
dtype: int64

In [28]:
#replace null with male

In [29]:
ti = ti.replace('hi', 'male')
ti.head()

Survived  Pclass     Sex    Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.00      1      0   7.2500        S
1         1       1  female  35.00      1      0  71.2833        C
2         1       3    male  26.00      0      0   7.9250        S
4         0       3    male   0.35      0      0   8.0500        S
5         0       3    male  28.00      0      0   8.4583        Q

In [30]:
# Now, there should be male and female in the Sex column

# chaing categorical values with map
ti['Sex'] = ti['Sex'].map({'female': 0, 'male': 1})
ti.head()

Survived  Pclass  Sex    Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.00      1      0   7.2500        S
1         1       1    0  35.00      1      0  71.2833        C
2         1       3    1  26.00      0      0   7.9250        S
4         0       3    1   0.35      0      0   8.0500        S
5         0       3    1  28.00      0      0   8.4583        Q

In [31]:
# when you analyze data, it is better to transform categorical values to numerical values
# can you convert S, C, Q (Embarked) to 1, 2, 3
ti['Emarked'] = ti['Embarked'].map({'S': 1, 'C': 2, 'Q' : 3})
ti.head()

Survived  Pclass  Sex    Age  SibSp  Parch     Fare Embarked  Emarked
0         0       3    1  22.00      1      0   7.2500        S        1
1         1       1    0  35.00      1      0  71.2833        C        2
2         1       3    1  26.00      0      0   7.9250        S        1
4         0       3    1   0.35      0      0   8.0500        S        1
5         0       3    1  28.00      0      0   8.4583        Q        3

After applying multiple techniques of data cleaning, the data looks good now. Perhaps, this cleaned data can be used for analysis & builing predictive model.
The predictive model would predict who is likely to survive, while using Survived as y value

In [32]:
# if the data cleaning is done, you may want to export it as csv or excel

ti.to_csv("data/ti_cleaned.csv")

# Intermediate-level Data Transformation

In [33]:
# create new columns
ti['CurrentAge'] = ti['Age'] + 90
ti.head()

Survived  Pclass  Sex    Age  SibSp  Parch     Fare Embarked  Emarked  \
0         0       3    1  22.00      1      0   7.2500        S        1   
1         1       1    0  35.00      1      0  71.2833        C        2   
2         1       3    1  26.00      0      0   7.9250        S        1   
4         0       3    1   0.35      0      0   8.0500        S        1   
5         0       3    1  28.00      0      0   8.4583        Q        3   

   CurrentAge  
0      112.00  
1      125.00  
2      116.00  
4       90.35  
5      118.00

In [34]:
# can you create a new column ("discount") based on Fare?
ti['Discount'] = ti['Fare'] * 0.25
ti.head()

Survived  Pclass  Sex    Age  SibSp  Parch     Fare Embarked  Emarked  \
0         0       3    1  22.00      1      0   7.2500        S        1   
1         1       1    0  35.00      1      0  71.2833        C        2   
2         1       3    1  26.00      0      0   7.9250        S        1   
4         0       3    1   0.35      0      0   8.0500        S        1   
5         0       3    1  28.00      0      0   8.4583        Q        3   

   CurrentAge   Discount  
0      112.00   1.812500  
1      125.00  17.820825  
2      116.00   1.981250  
4       90.35   2.012500  
5      118.00   2.114575

In [35]:
# create a copy of existing column
ti['DeparturePort'] = ti['Embarked']
ti.head()

Survived  Pclass  Sex    Age  SibSp  Parch     Fare Embarked  Emarked  \
0         0       3    1  22.00      1      0   7.2500        S        1   
1         1       1    0  35.00      1      0  71.2833        C        2   
2         1       3    1  26.00      0      0   7.9250        S        1   
4         0       3    1   0.35      0      0   8.0500        S        1   
5         0       3    1  28.00      0      0   8.4583        Q        3   

   CurrentAge   Discount DeparturePort  
0      112.00   1.812500             S  
1      125.00  17.820825             C  
2      116.00   1.981250             S  
4       90.35   2.012500             S  
5      118.00   2.114575             Q

In [36]:
# rename columns
ti = ti.rename(columns={'Pclass': 'PassengerClass'})
ti.head()

Survived  PassengerClass  Sex    Age  SibSp  Parch     Fare Embarked  \
0         0               3    1  22.00      1      0   7.2500        S   
1         1               1    0  35.00      1      0  71.2833        C   
2         1               3    1  26.00      0      0   7.9250        S   
4         0               3    1   0.35      0      0   8.0500        S   
5         0               3    1  28.00      0      0   8.4583        Q   

   Emarked  CurrentAge   Discount DeparturePort  
0        1      112.00   1.812500             S  
1        2      125.00  17.820825             C  
2        1      116.00   1.981250             S  
4        1       90.35   2.012500             S  
5        3      118.00   2.114575             Q

In [37]:
# Can you rename discount as Disc
ti = ti.rename(columns={'Discount': 'Disc'})
ti.head()

Survived  PassengerClass  Sex    Age  SibSp  Parch     Fare Embarked  \
0         0               3    1  22.00      1      0   7.2500        S   
1         1               1    0  35.00      1      0  71.2833        C   
2         1               3    1  26.00      0      0   7.9250        S   
4         0               3    1   0.35      0      0   8.0500        S   
5         0               3    1  28.00      0      0   8.4583        Q   

   Emarked  CurrentAge       Disc DeparturePort  
0        1      112.00   1.812500             S  
1        2      125.00  17.820825             C  
2        1      116.00   1.981250             S  
4        1       90.35   2.012500             S  
5        3      118.00   2.114575             Q

In [38]:
# create bins (discretize)

ti['Fare_Category'] = pd.qcut(ti['Fare'], 5)
ti.head()

Survived  PassengerClass  Sex    Age  SibSp  Parch     Fare Embarked  \
0         0               3    1  22.00      1      0   7.2500        S   
1         1               1    0  35.00      1      0  71.2833        C   
2         1               3    1  26.00      0      0   7.9250        S   
4         0               3    1   0.35      0      0   8.0500        S   
5         0               3    1  28.00      0      0   8.4583        Q   

   Emarked  CurrentAge       Disc DeparturePort      Fare_Category  
0        1      112.00   1.812500             S    (-0.001, 7.854]  
1        2      125.00  17.820825             C  (39.688, 512.329]  
2        1      116.00   1.981250             S      (7.854, 10.5]  
4        1       90.35   2.012500             S      (7.854, 10.5]  
5        3      118.00   2.114575             Q      (7.854, 10.5]

In [39]:
ti.groupby('Fare_Category').count()

Survived  PassengerClass  Sex  Age  SibSp  Parch  Fare  \
Fare_Category                                                               
(-0.001, 7.854]         179             179  179  179    179    179   179   
(7.854, 10.5]           184             184  184  184    184    184   184   
(10.5, 21.317]          171             171  171  171    171    171   171   
(21.317, 39.688]        181             181  181  181    181    181   181   
(39.688, 512.329]       175             175  175  175    175    175   175   

                   Embarked  Emarked  CurrentAge  Disc  DeparturePort  
Fare_Category                                                          
(-0.001, 7.854]         179      179         179   179            179  
(7.854, 10.5]           184      184         184   184            184  
(10.5, 21.317]          171      171         171   171            171  
(21.317, 39.688]        181      181         181   181            181  
(39.688, 512.329]       175      175         175   175            175

In [40]:
#rename the name of those bins to 1, 2, 3, 4, 5
ti['Fare_Category_Labels'] = pd.qcut(ti['Fare'], 5, labels=['1', '2', '3', '4', '5'])
ti.head()

Survived  PassengerClass  Sex    Age  SibSp  Parch     Fare Embarked  \
0         0               3    1  22.00      1      0   7.2500        S   
1         1               1    0  35.00      1      0  71.2833        C   
2         1               3    1  26.00      0      0   7.9250        S   
4         0               3    1   0.35      0      0   8.0500        S   
5         0               3    1  28.00      0      0   8.4583        Q   

   Emarked  CurrentAge       Disc DeparturePort      Fare_Category  \
0        1      112.00   1.812500             S    (-0.001, 7.854]   
1        2      125.00  17.820825             C  (39.688, 512.329]   
2        1      116.00   1.981250             S      (7.854, 10.5]   
4        1       90.35   2.012500             S      (7.854, 10.5]   
5        3      118.00   2.114575             Q      (7.854, 10.5]   

  Fare_Category_Labels  
0                    1  
1                    5  
2                    2  
4                    2  
5                    2

In [41]:
#Survived is categorical data type. What if I want to change it to integer
ti['Survived'] = ti['Survived'].astype(int)
ti.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 890 entries, 0 to 890
Data columns (total 14 columns):
Survived                890 non-null int32
PassengerClass          890 non-null int64
Sex                     890 non-null int64
Age                     890 non-null float64
SibSp                   890 non-null int64
Parch                   890 non-null int64
Fare                    890 non-null float64
Embarked                890 non-null object
Emarked                 890 non-null int64
CurrentAge              890 non-null float64
Disc                    890 non-null float64
DeparturePort           890 non-null object
Fare_Category           890 non-null category
Fare_Category_Labels    890 non-null category
dtypes: category(2), float64(4), int32(1), int64(5), object(2)
memory usage: 88.9+ KB


In [42]:
# filtering or selecting columns

#selecting two columns and assigning to a new variable or dataset called "ti_2"
ti_2 = ti[['Survived','Age']]
ti_2.head()

Survived    Age
0         0  22.00
1         1  35.00
2         1  26.00
4         0   0.35
5         0  28.00

In [43]:
# can you select two other columns. use a different variable name (ti_3)
ti_3 = ti[['Sex','DeparturePort']]
ti_3.head()

Sex DeparturePort
0    1             S
1    0             C
2    1             S
4    1             S
5    1             Q

In [44]:
# Filtering or Selecting rows

#single criterion
ti[(ti['Fare'] > 200)]

Survived  PassengerClass  Sex   Age  SibSp  Parch      Fare Embarked  \
27          0               1    1  19.0      3      2  263.0000        S   
88          1               1    0  23.0      3      2  263.0000        S   
118         0               1    1  24.0      0      1  247.5208        C   
258         1               1    0  35.0      0      0  512.3292        C   
299         1               1    0  50.0      0      1  247.5208        C   
311         1               1    0  18.0      2      2  262.3750        C   
341         1               1    0  24.0      3      2  263.0000        S   
377         0               1    1  27.0      0      2  211.5000        C   
380         1               1    0  42.0      0      0  227.5250        C   
438         0               1    1  64.0      1      4  263.0000        S   
527         0               1    1  28.0      0      0  221.7792        S   
557         0               1    1  28.0      0      0  227.5250        C   
679         1               1    1  36.0      0      1  512.3292        C   
689         1               1    0  15.0      0      1  211.3375        S   
700         1               1    0  18.0      1      0  227.5250        C   
716         1               1    0  38.0      0      0  227.5250        C   
730         1               1    0  29.0      0      0  211.3375        S   
737         1               1    1  35.0      0      0  512.3292        C   
742         1               1    0  21.0      2      2  262.3750        C   
779         1               1    0  43.0      0      1  211.3375        S   

     Emarked  CurrentAge        Disc DeparturePort      Fare_Category  \
27         1       109.0   65.750000             S  (39.688, 512.329]   
88         1       113.0   65.750000             S  (39.688, 512.329]   
118        2       114.0   61.880200             C  (39.688, 512.329]   
258        2       125.0  128.082300             C  (39.688, 512.329]   
299        2       140.0   61.880200             C  (39.688, 512.329]   
311        2       108.0   65.593750             C  (39.688, 512.329]   
341        1       114.0   65.750000             S  (39.688, 512.329]   
377        2       117.0   52.875000             C  (39.688, 512.329]   
380        2       132.0   56.881250             C  (39.688, 512.329]   
438        1       154.0   65.750000             S  (39.688, 512.329]   
527        1       118.0   55.444800             S  (39.688, 512.329]   
557        2       118.0   56.881250             C  (39.688, 512.329]   
679        2       126.0  128.082300             C  (39.688, 512.329]   
689        1       105.0   52.834375             S  (39.688, 512.329]   
700        2       108.0   56.881250             C  (39.688, 512.329]   
716        2       128.0   56.881250             C  (39.688, 512.329]   
730        1       119.0   52.834375             S  (39.688, 512.329]   
737        2       125.0  128.082300             C  (39.688, 512.329]   
742        2       111.0   65.593750             C  (39.688, 512.329]   
779        1       133.0   52.834375             S  (39.688, 512.329]   

    Fare_Category_Labels  
27                     5  
88                     5  
118                    5  
258                    5  
299                    5  
311                    5  
341                    5  
377                    5  
380                    5  
438                    5  
527                    5  
557                    5  
679                    5  
689                    5  
700                    5  
716                    5  
730                    5  
737                    5  
742                    5  
779                    5

In [45]:
#Multiple conditions have to be combined using & 
ti[(ti['Fare'] > 200) & (ti['Survived'] == 1)]

Survived  PassengerClass  Sex   Age  SibSp  Parch      Fare Embarked  \
88          1               1    0  23.0      3      2  263.0000        S   
258         1               1    0  35.0      0      0  512.3292        C   
299         1               1    0  50.0      0      1  247.5208        C   
311         1               1    0  18.0      2      2  262.3750        C   
341         1               1    0  24.0      3      2  263.0000        S   
380         1               1    0  42.0      0      0  227.5250        C   
679         1               1    1  36.0      0      1  512.3292        C   
689         1               1    0  15.0      0      1  211.3375        S   
700         1               1    0  18.0      1      0  227.5250        C   
716         1               1    0  38.0      0      0  227.5250        C   
730         1               1    0  29.0      0      0  211.3375        S   
737         1               1    1  35.0      0      0  512.3292        C   
742         1               1    0  21.0      2      2  262.3750        C   
779         1               1    0  43.0      0      1  211.3375        S   

     Emarked  CurrentAge        Disc DeparturePort      Fare_Category  \
88         1       113.0   65.750000             S  (39.688, 512.329]   
258        2       125.0  128.082300             C  (39.688, 512.329]   
299        2       140.0   61.880200             C  (39.688, 512.329]   
311        2       108.0   65.593750             C  (39.688, 512.329]   
341        1       114.0   65.750000             S  (39.688, 512.329]   
380        2       132.0   56.881250             C  (39.688, 512.329]   
679        2       126.0  128.082300             C  (39.688, 512.329]   
689        1       105.0   52.834375             S  (39.688, 512.329]   
700        2       108.0   56.881250             C  (39.688, 512.329]   
716        2       128.0   56.881250             C  (39.688, 512.329]   
730        1       119.0   52.834375             S  (39.688, 512.329]   
737        2       125.0  128.082300             C  (39.688, 512.329]   
742        2       111.0   65.593750             C  (39.688, 512.329]   
779        1       133.0   52.834375             S  (39.688, 512.329]   

    Fare_Category_Labels  
88                     5  
258                    5  
299                    5  
311                    5  
341                    5  
380                    5  
679                    5  
689                    5  
700                    5  
716                    5  
730                    5  
737                    5  
742                    5  
779                    5

Some passengers in upper class did not survived.

In [46]:
# can you create a filter using a criterion?
ti[(ti['Sex'] == 1)]

Survived  PassengerClass  Sex    Age  SibSp  Parch      Fare Embarked  \
0           0               3    1  22.00      1      0    7.2500        S   
2           1               3    1  26.00      0      0    7.9250        S   
4           0               3    1   0.35      0      0    8.0500        S   
5           0               3    1  28.00      0      0    8.4583        Q   
6           0               1    1  54.00      0      0   51.8625        S   
7           0               3    1   2.00      3      1   21.0750        S   
12          0               3    1  20.00      0      0    8.0500        S   
13          0               3    1  39.00      1      5   31.2750        S   
16          0               3    1   2.00      4      1   29.1250        Q   
17          1               2    1  28.00      0      0   13.0000        S   
20          0               2    1  35.00      0      0   26.0000        S   
21          1               2    1  34.00      0      0   13.0000        S   
23          1               1    1  28.00      0      0   35.5000        S   
26          0               3    1  28.00      0      0    7.2250        C   
27          0               1    1  19.00      3      2  263.0000        S   
29          0               3    1  28.00      0      0    7.8958        S   
30          0               1    1  40.00      0      0   27.7208        C   
33          0               2    1  66.00      0      0   10.5000        S   
34          0               1    1  28.00      1      0   82.1708        C   
35          0               1    1  42.00      1      0   52.0000        S   
36          1               3    1  28.00      0      0    7.2292        C   
37          0               3    1  21.00      0      0    8.0500        S   
42          0               3    1  28.00      0      0    7.8958        C   
45          0               3    1  28.00      0      0    8.0500        S   
46          0               3    1  28.00      1      0   15.5000        Q   
48          0               3    1  28.00      2      0   21.6792        C   
50          0               3    1   7.00      4      1   39.6875        S   
51          0               3    1  21.00      0      0    7.8000        S   
54          0               1    1  65.00      0      1   61.9792        C   
55          1               1    1  28.00      0      0   35.5000        S   
..        ...             ...  ...    ...    ...    ...       ...      ...   
840         0               3    1  20.00      0      0    7.9250        S   
841         0               2    1  16.00      0      0   10.5000        S   
843         0               3    1  34.50      0      0    6.4375        C   
844         0               3    1  17.00      0      0    8.6625        S   
845         0               3    1  42.00      0      0    7.5500        S   
846         0               3    1  28.00      8      2   69.5500        S   
847         0               3    1  35.00      0      0    7.8958        C   
848         0               2    1  28.00      0      1   33.0000        S   
850         0               3    1   4.00      4      2   31.2750        S   
851         0               3    1  74.00      0      0    7.7750        S   
857         1               1    1  51.00      0      0   26.5500        S   
859         0               3    1  28.00      0      0    7.2292        C   
860         0               3    1  41.00      2      0   14.1083        S   
861         0               2    1  21.00      1      0   11.5000        S   
864         0               2    1  24.00      0      0   13.0000        S   
867         0               1    1  31.00      0      0   50.4958        S   
868         0               3    1  28.00      0      0    9.5000        S   
869         1               3    1   4.00      1      1   11.1333        S   
870         0               3    1  26.00      0      0    7.8958        S   
872         0              

In [47]:
# sampling data randomly

# sampling 10 rows only (different samples for every time you run this cell)
ti_10 = ti.sample(10)
ti_10

# to have the same samples for every time 
ti.sample(10, random_state = 1)

Survived  PassengerClass  Sex    Age  SibSp  Parch     Fare Embarked  \
862         1               1    0  48.00      0      0  25.9292        S   
224         1               1    1  38.00      1      0  90.0000        S   
85          1               3    0  33.00      3      0  15.8500        S   
680         0               3    0  28.00      0      0   8.1375        Q   
536         0               1    1  45.00      0      0  26.5500        S   
623         0               3    1  21.00      0      0   7.8542        S   
149         0               2    1  42.00      0      0  13.0000        S   
4           0               3    1   0.35      0      0   8.0500        S   
35          0               1    1  42.00      1      0  52.0000        S   
242         0               2    1  29.00      0      0  10.5000        S   

     Emarked  CurrentAge       Disc DeparturePort      Fare_Category  \
862        1      138.00   6.482300             S   (21.317, 39.688]   
224        1      128.00  22.500000             S  (39.688, 512.329]   
85         1      123.00   3.962500             S     (10.5, 21.317]   
680        3      118.00   2.034375             Q      (7.854, 10.5]   
536        1      135.00   6.637500             S   (21.317, 39.688]   
623        1      111.00   1.963550             S    (-0.001, 7.854]   
149        1      132.00   3.250000             S     (10.5, 21.317]   
4          1       90.35   2.012500             S      (7.854, 10.5]   
35         1      132.00  13.000000             S  (39.688, 512.329]   
242        1      119.00   2.625000             S      (7.854, 10.5]   

    Fare_Category_Labels  
862                    4  
224                    5  
85                     3  
680                    2  
536                    4  
623                    1  
149                    3  
4                      2  
35                     5  
242                    2

In [48]:
# sort data by column

#sorting: ascending=True is the default
ti_10.sort_values('Fare').head()

Survived  PassengerClass  Sex   Age  SibSp  Parch    Fare Embarked  \
553         1               3    1  22.0      0      0  7.2250        C   
352         0               3    1  15.0      1      1  7.2292        C   
420         0               3    1  28.0      0      0  7.8958        C   
101         0               3    1  28.0      0      0  7.8958        S   
2           1               3    1  26.0      0      0  7.9250        S   

     Emarked  CurrentAge     Disc DeparturePort    Fare_Category  \
553        2       112.0  1.80625             C  (-0.001, 7.854]   
352        2       105.0  1.80730             C  (-0.001, 7.854]   
420        2       118.0  1.97395             C    (7.854, 10.5]   
101        1       118.0  1.97395             S    (7.854, 10.5]   
2          1       116.0  1.98125             S    (7.854, 10.5]   

    Fare_Category_Labels  
553                    1  
352                    1  
420                    2  
101                    2  
2                      2

In [49]:
ti_10.sort_values(by=['Fare'], ascending=False).head()

Survived  PassengerClass  Sex   Age  SibSp  Parch     Fare Embarked  \
849         1               1    0  28.0      1      0  89.1042        C   
724         1               1    1  27.0      1      0  53.1000        S   
637         0               2    1  31.0      1      1  26.2500        S   
418         0               2    1  30.0      0      0  13.0000        S   
226         1               2    1  19.0      0      0  10.5000        S   

     Emarked  CurrentAge      Disc DeparturePort      Fare_Category  \
849        2       118.0  22.27605             C  (39.688, 512.329]   
724        1       117.0  13.27500             S  (39.688, 512.329]   
637        1       121.0   6.56250             S   (21.317, 39.688]   
418        1       120.0   3.25000             S     (10.5, 21.317]   
226        1       109.0   2.62500             S      (7.854, 10.5]   

    Fare_Category_Labels  
849                    5  
724                    5  
637                    4  
418                    3  
226                    2

In [50]:
# Ascending by first column, then descending by second column
ti_10.sort_values(by=['Survived','Age'], ascending=[1,0])

Survived  PassengerClass  Sex   Age  SibSp  Parch     Fare Embarked  \
637         0               2    1  31.0      1      1  26.2500        S   
418         0               2    1  30.0      0      0  13.0000        S   
420         0               3    1  28.0      0      0   7.8958        C   
101         0               3    1  28.0      0      0   7.8958        S   
352         0               3    1  15.0      1      1   7.2292        C   
849         1               1    0  28.0      1      0  89.1042        C   
724         1               1    1  27.0      1      0  53.1000        S   
2           1               3    1  26.0      0      0   7.9250        S   
553         1               3    1  22.0      0      0   7.2250        C   
226         1               2    1  19.0      0      0  10.5000        S   

     Emarked  CurrentAge      Disc DeparturePort      Fare_Category  \
637        1       121.0   6.56250             S   (21.317, 39.688]   
418        1       120.0   3.25000             S     (10.5, 21.317]   
420        2       118.0   1.97395             C      (7.854, 10.5]   
101        1       118.0   1.97395             S      (7.854, 10.5]   
352        2       105.0   1.80730             C    (-0.001, 7.854]   
849        2       118.0  22.27605             C  (39.688, 512.329]   
724        1       117.0  13.27500             S  (39.688, 512.329]   
2          1       116.0   1.98125             S      (7.854, 10.5]   
553        2       112.0   1.80625             C    (-0.001, 7.854]   
226        1       109.0   2.62500             S      (7.854, 10.5]   

    Fare_Category_Labels  
637                    4  
418                    3  
420                    2  
101                    2  
352                    1  
849                    5  
724                    5  
2                      2  
553                    1  
226                    2

In [51]:
# you can expport this sample data 

ti_10.to_csv("data/ti_10.csv")

In [52]:
# can you sample 50 rows?
ti_50 = ti.sample(50)
ti_50.head(1)

Survived  PassengerClass  Sex   Age  SibSp  Parch   Fare Embarked  \
307         1               1    0  17.0      1      0  108.9        C   

     Emarked  CurrentAge    Disc DeparturePort      Fare_Category  \
307        2       107.0  27.225             C  (39.688, 512.329]   

    Fare_Category_Labels  
307                    5

In [53]:
# apply sorting (descending, ascending)
ti_50.sort_values(by=['PassengerClass','Age'], ascending=[0,1]).head()

Survived  PassengerClass  Sex   Age  SibSp  Parch     Fare Embarked  \
348         1               3    1   3.0      1      1  15.9000        S   
702         0               3    0  18.0      0      1  14.4542        C   
646         0               3    1  19.0      0      0   7.8958        S   
622         1               3    1  20.0      1      1  15.7417        C   
652         0               3    1  21.0      0      0   8.4333        S   

     Emarked  CurrentAge      Disc DeparturePort   Fare_Category  \
348        1        93.0  3.975000             S  (10.5, 21.317]   
702        2       108.0  3.613550             C  (10.5, 21.317]   
646        1       109.0  1.973950             S   (7.854, 10.5]   
622        2       110.0  3.935425             C  (10.5, 21.317]   
652        1       111.0  2.108325             S   (7.854, 10.5]   

    Fare_Category_Labels  
348                    3  
702                    3  
646                    2  
622                    3  
652                    2

References
- Cleaning Big Data: Most Time-Consuming, Least Enjoyable Data Science Task, Survey Sayshttp://www.forbes.com/sites/gilpress/2016/03/23/data-preparation-most-time-consuming-least-enjoyable-data-science-task-survey-says/#62eb1cc37f75